### ISSUE TITLE
能转换ASCII为中文吗 

### ISSUE THREAD

**Issue by bestv5** [suheng1921/PropertiesEditor#1]

**Comment by suheng1921** [comment]
>
仓库只是对Eclipse插件**PropertiesEditor**的copy备份（原插件链接在仓库简介中），插件的作用是把eclipse中的*.properties文件中的ASCII转换为中文显示，本地文件中保存的还是ASCII，如果你需要的是这个效果，那么回答是：可以
需要注意的是**PropertiesEditor**插件原作者已经很久不更新了，所以不确定它是否可以在最新版Eclipse中使用
